global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'email-microservice'
    static_configs:
      - targets: ['host.docker.internal:7070']

  - job_name: 'rabbitmq'
    scrape_interval: 60s
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']